definitions:
  common.Image:
    properties:
      cloud_name:
        type: string
      extension:
        type: string
      height:
        type: integer
      id:
        type: integer
      url:
        type: string
      width:
        type: integer
    type: object
  common.Settings:
    properties:
      language:
        type: string
      theme:
        type: string
    type: object
  common.UID:
    type: object
  common.successRes:
    properties:
      data: {}
      filter: {}
      message:
        type: string
      paging: {}
      status_code:
        type: integer
    type: object
  taskmodel.Task:
    properties:
      created_at:
        type: string
      deadline:
        type: string
      description:
        type: string
      id:
        $ref: '#/definitions/common.UID'
      name:
        type: string
      reminder:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  taskmodel.TaskCreate:
    properties:
      deadline:
        type: string
      description:
        type: string
      name:
        type: string
      reminder:
        type: string
    type: object
  taskmodel.TaskFind:
    properties:
      created_at:
        type: string
      deadline:
        type: string
      description:
        type: string
      id:
        $ref: '#/definitions/common.UID'
      name:
        type: string
      reminder:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  taskmodel.TaskUpdate:
    properties:
      deadline:
        type: string
      description:
        type: string
      name:
        type: string
      reminder:
        type: string
      status:
        type: string
    type: object
  tokenprovider.Token:
    properties:
      created:
        type: string
      expiry:
        type: integer
      token:
        type: string
    type: object
  uploadmodel.ImageUpload:
    properties:
      cloud_name:
        type: string
      created_by:
        type: integer
      extension:
        type: string
      height:
        type: integer
      id:
        type: integer
      url:
        type: string
      width:
        type: integer
    type: object
  usermodel.UserCreate:
    properties:
      avatar:
        $ref: '#/definitions/common.Image'
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      role:
        type: string
      settings:
        $ref: '#/definitions/common.Settings'
    type: object
  usermodel.UserUpdate:
    properties:
      avatar:
        $ref: '#/definitions/common.Image'
      name:
        type: string
      phone:
        type: string
      settings:
        $ref: '#/definitions/common.Settings'
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: User use email and password to login to system
      parameters:
      - description: Email address
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: '#/definitions/tokenprovider.Token'
      summary: Basic Login
  /api/register:
    post:
      consumes:
      - application/json
      description: User create new Account by providing email and password
      parameters:
      - description: Email address
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Phone
        in: formData
        name: phone
        required: true
        type: string
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sign up Success
          schema:
            $ref: '#/definitions/usermodel.UserCreate'
      summary: Basic Register
  /api/task:
    get:
      consumes:
      - application/json
      description: User Get List User's Task after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Page number
        in: path
        name: page
        required: true
        type: number
      - description: Limit of tasks returned!
        in: path
        name: limit
        required: true
        type: number
      - description: Task Id
        in: path
        name: cursor
        required: true
        type: string
      - description: Deadline
        in: path
        name: deadline
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully!
          schema:
            items:
              $ref: '#/definitions/taskmodel.Task'
            type: array
      summary: Get List User's Task
      tags:
      - Tasks
  /api/task/:
    post:
      consumes:
      - application/json
      description: User Create New Task after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task Name
        in: formData
        name: name
        required: true
        type: string
      - description: Description
        in: formData
        name: description
        required: true
        type: string
      - description: Deadline
        in: formData
        name: deadline
        required: true
        type: string
      - description: Reminder
        in: formData
        name: reminder
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created task!
          schema:
            $ref: '#/definitions/taskmodel.TaskCreate'
      summary: User Create New Task
      tags:
      - Tasks
  /api/task/:id:
    delete:
      consumes:
      - application/json
      description: User Deleted Task after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted task!
          schema:
            $ref: '#/definitions/common.successRes'
      summary: User Deleted Task
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: User Find Task after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully!
          schema:
            $ref: '#/definitions/taskmodel.TaskFind'
      summary: User Find Task
      tags:
      - Tasks
    patch:
      consumes:
      - application/json
      description: User Update Task after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task Id
        in: path
        name: id
        required: true
        type: string
      - description: Task Name
        in: formData
        name: name
        required: true
        type: string
      - description: Description
        in: formData
        name: description
        required: true
        type: string
      - description: Deadline
        in: formData
        name: deadline
        required: true
        type: string
      - description: Reminder
        in: formData
        name: reminder
        required: true
        type: string
      - description: Status
        in: formData
        name: status
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully update task!
          schema:
            $ref: '#/definitions/taskmodel.TaskUpdate'
      summary: User Update Task
      tags:
      - Tasks
  /api/users/profile:
    get:
      consumes:
      - application/json
      description: User get profile after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Update Profile Successfully
          schema: {}
      summary: User Get Profile
      tags:
      - Users
    patch:
      consumes:
      - application/json
      description: User update profile after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Phone
        in: formData
        name: phone
        required: true
        type: string
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Settings
        in: formData
        name: settings
        required: true
        type: string
      - description: Image
        in: formData
        name: image
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Update Profile Successfully
          schema:
            $ref: '#/definitions/usermodel.UserUpdate'
      summary: User Update Profile
      tags:
      - Users
  /api/users/upload:
    post:
      consumes:
      - application/json
      description: User upload photo after successful authentication.
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Image
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Upload Successfully
          schema:
            $ref: '#/definitions/uploadmodel.ImageUpload'
      summary: User Upload Photo
      tags:
      - Users
swagger: "2.0"
